### ISSUE TITLE
Add tdp restart command

### ISSUE THREAD

**Issue by GuillaumeHold** [TOSIT-IO/tdp-lib#245]
To manage restart of services in case of changes or failure of components, a new `tdp restart` command is required.
Initially, a simple restart strategy can be used.
Latter, a rolling restart strategy with component check can be implemented as an option of `tdp restart`.

**Comment by rpignolet** [comment]
Currently we record service version deployed inside a `service_log` table in the database. The actual behavior is to write the version deployed of a service if any operation of this service is ran.

So either we add a `--restart` option to the `deploy` command and we also launch the `*_config` operations to have a "clean" restart which also applies any modification to the configuration, or we issue a new ` restart` command which does not write to database that the services have been restarted.

I think we want to do #203 before in order to be smart when writing service/component version deployed. IMO restart command should perform a deployment stored in the database.

Of course I'm open to other ideas.

**Comment by KaidoKopli** [comment]
#203 is closed now. Can we resume the discussion on this issue especially with all the new possibilities offered by TDP-lib?

**Comment by PaulFarault** [comment]
For me, everything mentioned in this issue have been implemented.

> To manage restart of services in case of changes or failure of components

`tdp stale --generate` allows to generate a list of stale components that need to be reconfigured. Then, one can either reconfigure and restart the whole list using `tdp plan reconfigure` or launch individual operations using `tdp plan run`. The stale component list will be updated according to what operations are launched.

In case of a component failure, you can also use the `tdp plan run` command to launch required operations.

> Latter, a rolling restart strategy with component check can be implemented as an option

A `--rolling-restart` option has been added to `tdp plan reconfigure` by #395 and a PR is open to add it also on `tdp plan run` (#434)

Those commands can still be improved but IMO this issue is not relevant anymore. Did you think about anything else @KaidoKopli?

**Comment by PaulFarault** [comment]
@GuillaumeHold could we close this issue?
