### ISSUE TITLE
[meta] Add features for managing a running cluster

### ISSUE THREAD

**Issue by PACordonnier** [TOSIT-IO/tdp-lib#308]
TDP-Lib should be able to manage a cluster already deployed and not only deploy from scratch.

This includes:

- Stop/Start services on a single host (for maintenance purposes)
- Deploy on a single host (adding a new worker to a cluster) 
- Restart a single service on a single host (i.e: restart the current HBase Master) 
- Manage reconfiguration deployment and restart of required services as two asynchronous operation
  - Users should be able to rolling-restart the appropriate services
- Filter out the operation that are matched by 0 host.

This probably requires some change in the tdp-lib core:

- Add a setting that limits the deployment to a single host / a list of hosts / an ansible group (ex: worker) #307 
  - The version of the configuration deployed should per host and not per cluster (No issue yet)
- #318 
- Execution of a DeploymentPlan (or at least some of its operations) can be done in a rolling fashion (one operation every X seconds) #288 
- DeploymentPlan should be editable (#356)
- #348

**Comment by helenagodard** [comment]
Via TDP-lib, ability to Manage Configuration Groups, for each installed service (HDFS, YARN, HBASE,HIVE...)

For example, after deploying cluster with default configuration settings, each host belongs to one configuration group that has default configuration settings for the YARN service. Due to differences in the hardware, we should be able to create specific group and associate hosts in the most appropriate configGroup (like yarn_hardware_type_A/yarn_hardware_type_B,default...)
